stages:
    - linting
    - test

flake8:
    stage: linting
    image: registry.gitlab.com/pipeline-components/flake8:latest
    script:
        - pip install -r requirements/test.txt
        - flake8 --verbose .

black:
    stage: linting
    image: registry.gitlab.com/pipeline-components/black:latest
    script:
        - black --check --diff .

tests:
    stage: test
    image: python:3-slim
    script:
        - pip install -r requirements/test.txt
        - cd tracker
        - python manage.py test
